services:
  - type: web
    name: go-chatboot-suite
    env: docker
    region: ohio # Puedes cambiar a oregon o frankfurt según te convenga
    plan: free
    healthCheckPath: / # Opcional, pero ayuda a Render a saber si tu bot está vivo
    envVars:
      - key: PORT
        value: 8000
      - key: WEBHOOK_PATH
        value: /webhook
      # NO pongas tus tokens secretos aquí si el repo es público
