services:
  - type: web
    name: neuraforge-api
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    dockerfilePath: ./Dockerfile
  - type: worker
    name: neuraforge-error-bot
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    dockerfilePath: ./Dockerfile.bot
  - type: worker
    name: neuraforge-pagos-oxxo
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    dockerfilePath: ./Dockerfile.pagos
